.github/workflows/linux.yaml
Run `go fmt` and `go mod tidy` in GitHub Actions, and fail the test if they produce a diff.
=> run diff checks in CI

pkg/simpleradio/audio/client.go, pkg/simpleradio/audio/transmit.go
More accurately time when we write packets to reduce stutter during longer transmission.
=> improve SRS packet write timing to reduce stutter

docs/CONTRIBUTING.md, docs/PLAYER.md, go.mod, go.sum, pkg/brevity/snaplock.go, pkg/composer/braa.go, pkg/composer/group.go, pkg/composer/snaplock.go, pkg/controller/alphacheck.go, pkg/controller/bogeydope.go, pkg/controller/controller.go, pkg/controller/declare.go, pkg/controller/picture.go, pkg/controller/radiocheck.go, pkg/controller/snaplock.go, pkg/controller/spiked.go, pkg/encyclopedia/aircraft.go, pkg/parser/parser.go, pkg/parser/snaplock_test.go, pkg/radar/contacts.go, pkg/radar/contacts_test.go, pkg/radar/group.go, pkg/radar/id.go, pkg/radar/nearby.go, pkg/radar/nearest.go, pkg/radar/radar.go, pkg/recognizer/whisper.go, pkg/tacview/acmi/acmi.go
Closes #59 
Implement the SNAPLOCK command. To implement this command I had to change the signature of the `Radar.FindNearbyGroups` method, and to keep things consistent I've rewritten the interface so all of the "find" functions have similar arguments.
BONUS FEATURE: Callsign lookups in the contacts database now fall back on fuzzy search if an exact match fails.
=> implement snaplock

docs/CONTRIBUTING.md, docs/PLAYER.md, internal/application/app.go, pkg/controller/declare.go, pkg/controller/snaplock.go, pkg/controller/unable.go, pkg/parser/declare_test.go, pkg/parser/parser.go, pkg/parser/parser_test.go, pkg/radar/nearby.go, pkg/radar/radar.go, pkg/tacview/acmi/acmi.go
- Fix an issue where declare responses were in BRAA format instead of BULLSEYE format
- A lot of general parser tuning and improvements. In particular the callsign parser hbas been entirely rewritten. The ggml-tiny model is now viable, though the small model is still better quality if your PC can run it
- Callsign parsing is now more permissive, e.g. "Viking" with no numbers is now a valid callsign
- Removed some parser tests that weren't applicable to real world usage due to quality improvements in the recognizer (due to prompt engineering). Added some test cases for issues that came up during the test session.
- Suppressed the annoying warning for AI aircraft with no pilot names set.
=> improvments from hoggit/lima kilo testing

pkg/recognizer/whisper.go
Fixes #107 
By my math 256k is 16 seconds of audio at 16KHz which should be plenty long enough for any request.
=> Limit recognition to first 256k elements of sample

pkg/controller/alphacheck.go, pkg/controller/bogeydope.go, pkg/controller/declare.go, pkg/controller/picture.go, pkg/controller/radiocheck.go, pkg/controller/snaplock.go, pkg/controller/spiked.go, pkg/controller/unable.go, pkg/radar/contacts.go, pkg/radar/contacts_test.go, pkg/radar/grouping.go, pkg/radar/id.go, pkg/radar/radar.go
Prevent players from impersonating aircraft from the other coalition in requests.
Fixes #116
=> enforce requestor coalition

cmd/skyeye/main.go, internal/application/app.go, pkg/simpleradio/audio/client.go, pkg/simpleradio/audio/ping.go, pkg/simpleradio/audio/receive.go, pkg/simpleradio/client.go, pkg/simpleradio/data/client.go, pkg/tacview/acmi/acmi.go, pkg/tacview/client/client.go, pkg/tacview/client/file.go, pkg/tacview/client/telemetry.go
Drops the shift length feature for now because turns out it was doing broken things with UDP sockets
Add a synchronized waitgroup to the app as a first step towards a proper shutdown sequence with midnight callout
=> wait on waitgroup

pkg/brevity/group.go, pkg/radar/group.go
Remove references to weeds -- AIC shouldn't use "weeds" more of an AUX comm for fighters.
=> Remove Weeds

internal/application/app.go, pkg/radar/contacts.go, pkg/radar/faded.go, pkg/radar/radar.go
Run a routine which collects faded messages. It extends a 10-second timer each time it receives a fade message. Once this timer completes, all collected messages are grouped and published. This should fix getting 2 separate messages when a two-ship lands or is destroyed, assuming 10 seconds is a large enough window.
=> Collect fade notifcations into groups

docs/PLAYER.md, pkg/controller/picture.go
In DCS we can assume we are always cleared to engage the hostile coaltion, so hostile is the correct term rather than bandit.
=> Use 'hostile' instead of 'bandit'

docs/PLAYER.md, pkg/brevity/declare.go, pkg/controller/declare.go, pkg/parser/declare.go, pkg/parser/declare_test.go, pkg/parser/parser.go, pkg/parser/spatial.go
Allow users to provide DECLARE locations in BRAA format by saying "BRAA"  in front of the bearing.
If neither is provided, this assumes BULLSEYE.
Closes #106
=> Accept BRAA format in DECLARE

pkg/parser/parser.go, pkg/radar/contacts_test.go, pkg/radar/group.go, pkg/radar/radar.go, pkg/tacview/acmi/acmi.go, pkg/trackfiles/trackfile.go, pkg/trackfiles/trackfile_test.go
Using wall clock timestamps in trackfiles is mostly fine when reading telemetry in real-time, since the latency between the observation and reading the event is pretty low and usually consistent. However, it's problematic when replaying an old track.
Using mission timestamps instead should make it easier to do things like fast-forward though an ACMI file, then pause it to debug a specific scenario.
=> Remove real-time timestamp from trackfiles

docs/PLAYER.md, internal/application/app.go, pkg/coalitions/coalition.go, pkg/controller/alphacheck.go, pkg/controller/controller.go, pkg/controller/declare.go, pkg/parser/parser.go, pkg/radar/grouping.go, pkg/radar/radar.go, pkg/sim/sim.go, pkg/simpleradio/audio/transmit.go, pkg/tacview/acmi/acmi.go, pkg/tacview/client/client.go, pkg/tacview/client/file.go, pkg/tacview/client/telemetry.go, pkg/tacview/types/object.go
Bot didn't handle bullseyes for multiple coalitions correctly and would overwrite blue's bullseye with red's randomly. Most components now store a map of all bullseyes.
Interestingly, this may open the possibility of a single instance of Skyeye serving multiple coalitions as a post-launch feature... might be cool if we decide to seriously pursue PvP support in the future.
=> fix systemic issues handling bullseyes

pkg/encyclopedia/aircraft.go, pkg/encyclopedia/encyclopedia.go, pkg/radar/center.go, pkg/radar/group.go, pkg/radar/picture.go
Replace each aircraft's threat factor with a threat radius. The radius is easier to use in THREAT calls (#154) because it allows us to more easily scale the threat based on distance to arbitrary points.
Replace the PICTURE threat ranking algorithm. Before:
1. Armed over unarmed
2. Planes over helicopters
3. Mixture of distance, threat factor, altitude and size.
After:
1. Armed over unarmed
2. Planes over helicopters
3. Fighters, if they're inside the threat radius for their platform, over all others
4. Ratio of distance to threat radius for the platform, within 3NM margin
5. Distance, within 3NM margin
6. Altitude (pretty rare to make it this far - essentially need multiple groups of the same class of aircraft at the same distance)
=> Use scaled threat ranges to compare threat level

README.md, cmd/skyeye/main.go, docs/PLAYER.md, internal/application/app.go, internal/conf/configuration.go, pkg/brevity/group.go, pkg/brevity/threat.go, pkg/coalitions/coalition.go, pkg/composer/threat.go, pkg/controller/bogeydope.go, pkg/controller/controller.go, pkg/controller/declare.go, pkg/controller/faded.go, pkg/controller/picture.go, pkg/controller/snaplock.go, pkg/controller/spiked.go, pkg/controller/sunrise.go, pkg/controller/threat.go, pkg/encyclopedia/aircraft.go, pkg/parser/parser_test.go, pkg/radar/center.go, pkg/radar/group.go, pkg/radar/grouping.go, pkg/radar/id.go, pkg/radar/picture.go, pkg/radar/radar.go, pkg/radar/threat.go, pkg/simpleradio/client.go, pkg/simpleradio/data/client.go, pkg/synthesizer/speakers/piper.go
Implement a THREAT call system.
The radar has a new Threats method which returns a map of the hostile coalition's groups to UnitIDs they currently threaten.  Threat criteria is currently placeholder: within 35 NM, or within 100 NM and aspect Hot towards the unit.
The controller calls the Threat method every ten seconds. It iterates over the threats and checks if it's issued a call for that threat recently (it has a data structure tracking cooldown timers for each hostile group).
The controller now has a reference to the SRS client so it can check if a unit is on the bot's frequency before issuing a call.
=> Implement threat call system

pkg/brevity/altitude.go, pkg/brevity/altitude_test.go, pkg/brevity/braa.go, pkg/brevity/group.go, pkg/composer/group.go, pkg/radar/group.go, pkg/radar/grouping.go, pkg/radar/nearby.go, pkg/radar/nearest.go, pkg/radar/threat.go
Fixes #55.
Groups, BRA and BRAA now stores multiple altitudes. A new type called Stack organizes these altitudes into contact sub-groupings spaced 10,000 feet apart.
Groupings now span an unlimited vertical height, but also now check if the aircraft share one of the tags Fighter, Attack or Unarmed (if defined).
=> Implement altitude stacks

.vscode/settings.json
For some reason this broke my intellisense after 1.23 upgrade
=> Remove go.alternateTools setting

docs/PLAYER.md, pkg/brevity/group.go, pkg/controller/controller.go, pkg/controller/threat.go, pkg/radar/contacts.go, pkg/radar/contacts_test.go, pkg/radar/faded.go, pkg/radar/group.go, pkg/radar/grouping.go, pkg/radar/id.go, pkg/radar/nearby.go, pkg/radar/nearest.go, pkg/radar/radar.go, pkg/radar/threat.go, pkg/sim/sim.go, pkg/simpleradio/client.go, pkg/simpleradio/data/client.go, pkg/tacview/acmi/acmi.go, pkg/tacview/types/metadata.go, pkg/tacview/types/object.go, pkg/trackfiles/trackfile.go, pkg/trackfiles/trackfile_test.go
DCS/SRS and TacView IDs are separate domains and can't be directly compared. Split their usage up. If we need to check if someone is on SRS, best-guess by comparing the in-game name to the client name instead.
Fixes #218
=> Separate SRS and TacView IDs

go.mod, pkg/controller/declare.go, pkg/controller/snaplock.go, pkg/radar/nearby.go, pkg/radar/picture.go, pkg/radar/radar.go, pkg/radar/threat.go
- DECLARE/SNAPLOCK now examines the hostile and friendly groups which are closest to the point of interest
- The unit which initiated the request is excluded from the search
Fixes #275
=> Improve results of DECLARE/SNAPLOCK calls

docs/PLAYER.md, internal/application/app.go, pkg/brevity/group.go, pkg/brevity/merged.go, pkg/composer/composer.go, pkg/composer/group.go, pkg/composer/merged.go, pkg/controller/bogeydope.go, pkg/controller/broadcast.go, pkg/controller/controller.go, pkg/controller/declare.go, pkg/controller/merged.go, pkg/controller/merged_test.go, pkg/controller/picture.go, pkg/controller/snaplock.go, pkg/controller/threat.go, pkg/radar/callbacks.go, pkg/radar/group.go, pkg/radar/grouping.go, pkg/radar/merged.go, pkg/radar/radar.go, pkg/simpleradio/client.go, pkg/simpleradio/data/client.go
Fixes #186 and  #252
- Controller tracks which hostiles are merged with which friendlies.
- Merge status is tracked per-aircraft. For brevity purposes, a group is considered to be merged with every aircraft any single member of the group is merged with.
- Merge is entered when hostile and friendly are closer than 3 miles.
- Merge is exited when hostile and friendly are further than 7 miles.
- Merge status is removed if aircraft fades or the trackfile ages out.
- Controller broadcasts a MERGED call if friendlies on SRS merge with a hostile.
- Simple batching of merges that occur within 15 second windows. Not as fancy as the faded queuing behavior on the grounds that merge calls need to be broadcast quickly.
- May result in excessive number of calls during a large and complex furball.
- …
=> Implement MERGED calls

docs/PLAYER.md, pkg/controller/declare.go, pkg/parser/declare.go, pkg/parser/declare_test.go, pkg/parser/parser.go, pkg/parser/snaplock_test.go, pkg/parser/spatial.go
Related to #297 
- Fix a bug where altitude was not an optional field in a DECLARE request
- Allow the use of the separator words "for" "at" and "altitude" in a bullseye call
=> Improve DECLARE/SNAPLOCK parsing

pkg/parser/parser.go, pkg/parser/picture_test.go
It should be valid to accept a picture request that does not have an attached pilot callsign, for example:
"SKYEYE, PICTURE."
=> Allow Picture without a Pilot Callsign

pkg/composer/format.go, pkg/composer/format_test.go
AIC/ABMs don't use the civil aviation pronunciations of e.g. "tree"/"fower"/"ait", etc.
Further, it (at least in my opinion) makes it harder to understand particularly with the AI, it doesn't do a great job of saying "fower" for example.
=> Remove Civil Aviation Pronunciation

internal/cli/zerolog.go, pkg/tacview/acmi/acmi.go, pkg/tacview/types/coordinate.go, pkg/tacview/types/metadata.go, pkg/tacview/types/metadata_test.go, pkg/tacview/types/object.go, pkg/tacview/types/object_test.go
- Previously, we ignored any ACMI transform property which did not include longitude, latitude and altitude. Now, we properly handle transforms that only include one or two of these properties by merging them iwth any previous transform.
- Sometimes the ACMI data re-uses the same object ID for a different aircraft at a later point in time. Handle this case by explcitly removing the object if a property changes which should be static for the life of an aircraft, then publishing an explicitly new object. This should ensure that the downstream trackfile's labels are updated, even if trackfile didn't age out between the object lifecycles.
=> Handle partial transforms and re-used object IDs in ACMI data

docs/PLAYER.md, pkg/controller/callbacks.go, pkg/controller/controller.go, pkg/radar/callbacks.go, pkg/radar/faded.go
Suppress FADED calls for hostile aircraft which are greater than 55 miles away from any friendly. Rationale is that FADED is relevant for targeted aircraft and this is our current best proxy variable for a potentially targeted aircraft.
=> Only broadcast FADED calls when contact is near a friendly aircraft

Makefile, internal/application/app.go, pkg/controller/callbacks.go, pkg/radar/callbacks.go, pkg/radar/faded.go, pkg/radar/radar.go, pkg/radar/started.go, pkg/sim/sim.go, pkg/simpleradio/client.go, pkg/simpleradio/ping.go, pkg/tacview/client/client.go, pkg/tacview/client/interface.go, pkg/trackfiles/trackfile.go
- Added a `run` target to run SkyEye with data race detection
- Trackfile deques are now protected by a mutex
- Radar scope callbacks are now protected by a mutex
- SRS last ping time is now protected by a mutex
- Tacview client significantly modified
- Removed the `sim.Sim` interface in favor of `tacview.Client`
- Client now has dedicated goroutines for mission start events and aircraft removal events, resolving a race condition that could deadlock reading updates from tacview.
=> Correct various race conditions

pkg/brevity/merged.go, pkg/composer/group.go, pkg/composer/merged.go, pkg/controller/merged.go
Removed the contact count and friendly count from MERGED calls. Since we update the merged states before broadcasting the  calls, the calls were sequentially communicating the same final merged state instead of the intermediate states, which was confusing.
Closes #340
=> Simplify merged call

pkg/parser/parser.go, pkg/parser/parser_test.go
=> skip 'this is' when parsing callsigns

pkg/radar/faded.go, pkg/radar/radar.go, pkg/radar/started.go
Keep track of trackfile IDs that have faded in the last 5 minutes, and don't issue FADED calls for the same ID within that window.
Fixes #429
=> Deduplicate FADED calls

README.md, cmd/skyeye/main.go, config.yaml, docs/ADMIN.md, docs/PRIVACY.md, docs/QUICKSTART-HETZNER.md, docs/QUICKSTART-VULTR.md, docs/QUICKSTART-WINDOWS.md, go.mod, go.sum, internal/application/app.go, internal/conf/configuration.go, pkg/recognizer/openai.go, pkg/recognizer/prompt.go, pkg/recognizer/whisper.go
Adds two new configuration flags, `--recognizer` and `--openai-api-key`, which together allow the use of [OpenAI's Audio Transcription API](https://platform.openai.com/docs/api-reference/audio/createTranscription).
Resolves #163
=> Add support for OpenAI Transcription API

internal/application/compose.go, pkg/brevity/aspect.go, pkg/brevity/group.go, pkg/brevity/spiked.go, pkg/composer/composer.go, pkg/composer/faded.go, pkg/composer/group.go, pkg/composer/spiked.go, pkg/controller/spiked.go
Fixes #473 
~~**Requires incrementing module version to v2 due to API change in brevity.SpikedResponse**~~
=> Correct content of SPIKED response composition

pkg/controller/controller.go, pkg/controller/picture.go, pkg/radar/radar.go, pkg/trackfiles/trackfile.go
Fix two data races:
- Deadline to broadcast next picture was not protected and could be accessed from either the controller's ticker loop or the workload to handle a PICTURE request.
- Trackfile deque lock was acquired by LastKnown() and also functions which had LastKnown() in the call tree. Separated out an unsafe version of LastKnown() for internal use by those functions.
Fixes #522
=> Fix race conditions

Dockerfile
Install CA certificates in the container image so requests can be made to OpenAI. This was missed because generally people using the OpenAI API are running SkyEye on Windows as an extra process on their DCS server.
This sadly will require a rebuild every so often to update the ca-certificates package, unless the user bind-mounts their OS certs into the container.
Fixes #575
=> Install CA certificates in container
