- cmd/skyeye/main.go
- internal/application/app.go
- internal/conf/configuration.go
- pkg/radar/radar.go
- pkg/simpleradio/data/client.go
Asking the operator to provide frequency in Hz is unergonomic
> Provide frequency in MHz rather than Hz

- pkg/tacview/types/metadata.go
Fixes https://github.com/dharmab/skyeye/security/code-scanning/1
> Handle very large numbers in tacview data

- pkg/composer/group.go
> Use angels/cherubs brevity for friendly groups

- pkg/simpleradio/audio/transmit.go
Closes #61 
The SRS audio client's receive loop extends a deadline whenever an incoming voice packet is received. If this deadline is in the future, it means someone is talking on SRS and we shouldn't start a new transmission. If someone interrupts _us_, we'll continue to talk, because we only check the deadline at the start of the transmission.
> delay tx if rx deadline has not passed

- README.md
- docs/PRIVACY.md
> publish privacy statement

- pkg/trackfiles/trackfile.go
- pkg/trackfiles/trackfile_test.go
Use the mission time when computing trackfile movement rather than the wall clock time.
> Use mission time for trackfile computations rather than real time

- pkg/parser/parser.go
Use a string similarity algorithm to match GCI callsigns in case they're slightly misheard
Fixes #111
> Use edit distance thresholds for wake words

- docs/PLAYER.md
- internal/application/app.go
- pkg/brevity/faded.go
- pkg/composer/composer.go
- pkg/composer/faded.go
- pkg/controller/controller.go
- pkg/controller/picture.go
- pkg/radar/callbacks.go
- pkg/radar/grouping.go
- pkg/radar/nearby.go
- pkg/radar/nearest.go
- pkg/radar/picture.go
- pkg/radar/radar.go
> Implement FADED and VANISHED

- cmd/skyeye/main.go
- internal/application/app.go
- internal/conf/configuration.go
- pkg/parser/parser.go
- pkg/radar/contacts_test.go
- pkg/tacview/acmi/acmi.go
- pkg/tacview/client/client.go
- pkg/tacview/client/file.go
- pkg/tacview/client/telemetry.go
- Bot internally restarts after about two minutes if it appears the DCS server has restarted
- Bot automatically restarts after a configurable shift change
- If no callsign is selected, a random callsign is chosen at startup
- If no voice is selected, a random voice is chosen at startup
> Automatic shift changes and restarts

- cmd/skyeye/main.go
- internal/conf/configuration.go
Use a consistent callsign and voice for each 8 hour shift of the real time day
> stabilize callsigns into shifts

- cmd/skyeye/main.go
- docs/PLAYER.md
- internal/application/app.go
- internal/conf/configuration.go
- pkg/composer/faded.go
- pkg/composer/spiked.go
- pkg/controller/spiked.go
- pkg/controller/unable.go
- pkg/parser/bogeydope_test.go
- pkg/parser/declare_test.go
- pkg/parser/parser.go
- pkg/parser/parser_test.go
- pkg/parser/picture_test.go
- pkg/parser/snaplock_test.go
- pkg/parser/spatial.go
- pkg/parser/spiked_test.go
- pkg/radar/contacts.go
- pkg/radar/contacts_test.go
- pkg/radar/nearest.go
Rewrite the brevity parser using string similary matching instead of the horrible clusterfuck that was here before.
> Rewrite parser

- pkg/simpleradio/audio/transmit.go
Briefly pause between each transmission to signal the breaks between transmissions to players.
> Briefly pause between transmissions

- pkg/radar/contacts_test.go
> Add unit test for olympus style callsign

- cmd/skyeye/main.go
- docs/PLAYER.md
- internal/application/app.go
- internal/conf/configuration.go
- pkg/controller/controller.go
- pkg/controller/picture.go
Adds an optional feature to automatically broadcast a picture call at regular intervals. Requesting a picture will reset the interval timer.
> automatically broadcast picture

- internal/application/app.go
- pkg/brevity/group.go
- pkg/parser/parser.go
- pkg/radar/grouping.go
- pkg/radar/nearest.go
- pkg/radar/picture.go
- pkg/radar/radar.go
- pkg/simpleradio/audio/decode.go
- pkg/simpleradio/audio/encode.go
- pkg/simpleradio/audio/frame.go
- pkg/simpleradio/audio/receive.go
- pkg/simpleradio/audio/transmit.go
- pkg/simpleradio/data/client.go
- pkg/simpleradio/voice/packet.go
- pkg/synthesizer/speakers/piper.go
- pkg/tacview/acmi/acmi.go
- pkg/tacview/types/object.go
- pkg/trackfiles/trackfile.go
Remove a bunch of olf printf debugging from the early months of the project which were spamming the trace logs.
> clean up old debugging logs

- pkg/encyclopedia/aircraft.go
> Fix A-4 and AH-64 ACMI names

- pkg/bearings/bearing.go
- pkg/bearings/magnetic.go
- pkg/bearings/true.go
- pkg/brevity/aspect.go
- pkg/brevity/aspect_test.go
Fix an issue where aspects were often incorrectly computed.
> Fix aspect from angle function

- cmd/skyeye/main.go
- internal/application/app.go
- internal/conf/configuration.go
- pkg/radar/group.go
- pkg/radar/radar.go
- pkg/simpleradio/audio/client.go
- pkg/simpleradio/audio/ping.go
- pkg/simpleradio/audio/receive.go
- pkg/simpleradio/audio/transmit.go
- pkg/simpleradio/client.go
- pkg/simpleradio/data/client.go
- pkg/tacview/acmi/acmi.go
- pkg/tacview/client/client.go
- pkg/tacview/client/file.go
- pkg/tacview/client/telemetry.go
- pkg/trackfiles/trackfile.go
> Reconnect to tacview on EOF or other connection error

- internal/application/app.go
- pkg/bearings/declination.go
- pkg/controller/controller.go
- pkg/sim/sim.go
- pkg/tacview/acmi/acmi.go
- pkg/tacview/client/client.go
- pkg/tacview/types/metadata.go
Fixes a bug introduced in #148 which blocked the goroutine which updates the mission's time and the location of the bullseye points.
Fixes #192
> unblock time and bullseye thread

- pkg/controller/declare.go
- pkg/radar/center.go
- pkg/radar/group.go
- pkg/radar/grouping.go
- pkg/radar/nearby.go
- pkg/radar/nearest.go
- pkg/radar/picture.go
- pkg/radar/threat.go
- pkg/spatial/spatial.go
- pkg/spatial/spatial_test.go
- pkg/tacview/client/client.go
- pkg/trackfiles/trackfile.go
Create a new `spatial` package to deduplicate some common geometric math across the project.
> Move common geometric math to shared package

- go.mod
- pkg/coalitions/coalition.go
- pkg/radar/center.go
- pkg/radar/contacts.go
- pkg/radar/contacts_test.go
- pkg/radar/grouping.go
- pkg/radar/nearby.go
- pkg/radar/nearest.go
- pkg/radar/radar.go
Upgrade compiler and module version to Go 1.23. Replace custom trackfile iterator with shiny new standard library iterator.
Closes #184
> Upgrade to Go 1.23.0

- pkg/brevity/altitude.go
- pkg/brevity/altitude_test.go
- pkg/brevity/braa.go
- pkg/composer/group.go
- pkg/composer/spiked.go
- pkg/spatial/spatial.go
- pkg/spatial/spatial_test.go
> Round altitude to 100s if lower than 1000ft

- pkg/controller/controller.go
- pkg/controller/picture.go
> Don't repeatedly broadcast clean PICTURE

- .github/workflows/skyeye.yaml
- Dockerfile
- Makefile
> Create container image

- pkg/simpleradio/audio/transmit.go
> Fix anti-interupt transmission delay

- pkg/radar/radar.go
> do not age out zero-value timestamps

- pkg/brevity/altitude.go
- pkg/brevity/altitude_test.go
- pkg/radar/radar.go
> Remove minimum altitude filter

- docs/ADMIN.md
> Document AVX2 requirement

- docs/PLAYER.md
- pkg/brevity/radiocheck.go
- pkg/composer/radiocheck.go
- pkg/controller/radiocheck.go
> Reply to radio check even when callsign not on scope

- internal/application/app.go
- pkg/controller/controller.go
- pkg/radar/contacts.go
- pkg/radar/contacts_test.go
- pkg/radar/radar.go
- pkg/sim/sim.go
- pkg/tacview/acmi/acmi.go
- pkg/tacview/client/client.go
- pkg/tacview/client/file.go
- pkg/tacview/client/telemetry.go
- pkg/trackfiles/trackfile.go
> Clear trackfile database on mission restart

- .gitignore
- docs/ADMIN.md
- init/powershell/run-skyeye.ps1
- pkg/simpleradio/client.go
- pkg/simpleradio/net.go
- pkg/simpleradio/ping.go
- pkg/simpleradio/receive.go
- pkg/simpleradio/transmit.go
> automatically reconnect to SRS

- cmd/skyeye/main.go
- docs/PRIVACY.md
- internal/application/app.go
- internal/conf/configuration.go
- pkg/parser/bogeydope_test.go
- pkg/parser/declare_test.go
- pkg/parser/parser.go
- pkg/parser/parser_test.go
- pkg/parser/picture_test.go
- pkg/parser/snaplock_test.go
- pkg/parser/spiked_test.go
- pkg/recognizer/recognizer.go
- pkg/recognizer/whisper.go
- pkg/recognizer/whisper_test.go
> Allow transcriptions to be excluded from logs

- pkg/controller/controller.go
Before today, disabling automatic picture just set the interval to 117 hours
However it helps if you _actually use the field_ :sob:
> Fix disabling automatic picture

- .github/actions/build-container/action.yaml
- .github/workflows/skyeye.yaml
- .golangci.yaml
- Dockerfile
- Makefile
- cmd/skyeye-scaler/main.go
- cmd/skyeye/main.go
- docs/ADMIN.md
- init/winsw/skyeye-scaler-service.yaml
- internal/cli/enum.go
- internal/cli/simpleradio.go
- internal/cli/zerolog.go
- pkg/controller/controller.go
- pkg/simpleradio/client.go
- pkg/simpleradio/frequency.go
> Add a scaler tool

- .github/actions/build-container/action.yaml
> Fix image build target

- internal/application/compose.go
- pkg/brevity/alphacheck.go
- pkg/brevity/bogeydope.go
- pkg/brevity/contact.go
- pkg/brevity/declare.go
- pkg/brevity/faded.go
- pkg/brevity/merged.go
- pkg/brevity/picture.go
- pkg/brevity/radiocheck.go
- pkg/brevity/snaplock.go
- pkg/brevity/spiked.go
- pkg/brevity/sunrise.go
- pkg/brevity/threat.go
- pkg/brevity/tripwire.go
- pkg/brevity/unable.go
- pkg/composer/sunrise.go
- pkg/traces/context.go
- pkg/traces/discord.go
- pkg/traces/log.go
This line was more clutter than useful.
> Remove internal response line from trace report

- pkg/parser/parser.go
- pkg/parser/parser_test.go
> Skip 'request' when parsing callsign

- pkg/composer/group.go
- pkg/composer/merged.go
> adjust composition of merged calls

- pkg/composer/group.go
> remove extra common in stacks composition

- pkg/radar/faded.go
- pkg/radar/radar.go
> Don't age out trackfiles if faded calls may be pending

- cmd/skyeye/main.go
- config.yaml
- internal/application/app.go
- internal/conf/configuration.go
- pkg/synthesizer/speakers/piper.go
Float offers a wider range of customization values
> Change voice-playback-speed from enum to float

- .github/actions/build-whisper/action.yaml
- .github/workflows/skyeye.yaml
- Makefile
- docs/CONTRIBUTING.md
Add a CI workflow to build Skyeye on an Apple Sillicon mac.
> add macOS workflow to CI

- cmd/skyeye/main.go
- docs/PLAYER.md
- go.mod
- go.sum
- internal/application/app.go
- internal/conf/configuration.go
- pkg/commands/chat.go
- pkg/commands/request.go
- pkg/traces/context.go
- pkg/traces/discord.go
> Listen for GCI commands from in-game chat

- cmd/skyeye/main.go
- config.yaml
- internal/application/app.go
- internal/conf/configuration.go
> Use API key for gRPC authentication

- config.yaml
> Fix voice playback config comment

- .github/workflows/skyeye.yaml
- docs/ADMIN.md
- init/winsw/skyeye-scaler-service.yml
- init/winsw/skyeye-service.yml
> Fix misconfigured WinSW service definitions

- go.mod
- go.sum
- pkg/telemetry/handshake.go
- pkg/telemetry/handshake_test.go
- pkg/telemetry/telemetry.go
> Fix telemetry password hash algorithm

- pkg/telemetry/handshake.go
- pkg/telemetry/handshake_test.go
- pkg/telemetry/telemetry.go
> Toggle between CRC-64/ECMA and CRC-32/ISO-HDLC telemetry password hash algorithms

- pkg/parser/callsign.go
- pkg/parser/callsign_test.go
- pkg/parser/parser.go
- pkg/parser/parser_test.go
- pkg/parser/strings.go
- pkg/parser/strings_test.go
Split up the parser code in preparation for work on #434
> Split up parser code

- pkg/composer/declare.go
> Include fill-ins in DECLARE response

- pkg/bearings/declination.go
> Sample IGRF model warning log

- pkg/parser/callsign.go
- pkg/parser/callsign_test.go
> Ignore clan tags in pilot callsigns

- pkg/radar/merged.go
> Exclude invalid trackfiles from merges

- README.md
- cmd/skyeye/main.go
- docs/ADMIN.md
- go.mod
- go.sum
- internal/application/app.go
- internal/application/recognize.go
- internal/application/synthesize.go
- internal/conf/configuration.go
Resolves #502 
Related to #501
> Add options for acquiring file locks when running models

- pkg/composer/group.go
> Remove HIGH/LOW fill-ins if group has fewer than 3 contacts

- cmd/skyeye/main.go
> Fix enable-tracing flag

- config.yaml
- docs/ADMIN.md
- pkg/simpleradio/message.go
> Document EAM requirement

- README.md
- docs/PLAYER.md
- go.mod
- go.sum
- pkg/controller/callsigns.go
- pkg/controller/callsigns_test.go
- pkg/controller/merged.go
- pkg/controller/threat.go
- pkg/radar/id.go
> Collate flight and element callsigns

- pkg/recognizer/openai.go
> Fix regression in OpenAI API recognizer WAV serialization
